module.exports = {
  host: " brolandforever.aternos.me",
  //   host: " ami_404.aternos.me",
  port: 33779,
  //   port: 26673,
  username: "afkbot",
  owner: "DarkCode",
  prefix: "!",
  version: "1.21.1",
  autoRejoin: true,
  autoRejoinIn: 5 * 1000,
  diamondMilestone: 32,
  torchSpacing: 16,
  diamondReturnCount: 64,
};
